# this can be executed locally by calling
# gcloud builds submit --config cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "ls"
  args: ["-la", "/workspace"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - authorize
  - --allow-unauthenticated
  - --runtime=nodejs12
  - --trigger-http
  - --entry-point=authorize
  - --region=us-central1
  - --source=.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - get-auth-tokens
  - --allow-unauthenticated
  - --runtime=nodejs12
  - --trigger-http
  - --entry-point=getAuthTokens
  - --region=us-central1
  - --source=.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - get-analytics-accounts-list
  - --allow-unauthenticated
  - --runtime=nodejs12
  - --trigger-http
  - --entry-point=getAnalyticsAccountsList
  - --region=us-central1
  - --source=.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - get-tagmanager-accounts-list
  - --allow-unauthenticated
  - --runtime=nodejs12
  - --trigger-http
  - --entry-point=getTagmanagerAccountsList
  - --region=us-central1
  - --source=.
#  dir: 'functions/autodeploy'